
[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/gin-gonic/gin"
  version = "1.3.0"

# [[constraint]]
#   branch = "master"
#   name = "golang.org/x/net"

[[constraint]]
  name = "github.com/itsjamie/gin-cors"
  version = "1.0.0"

[[constraint]]
  name = "github.com/getsentry/raven-go"
  version = "0.2.0"
