apiVersion: v1
kind: Service
metadata:
  labels:
    app: gousers
    release: gousers
  name: gousers
  namespace: default
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 2369
  - name: https
    port: 443
    protocol: TCP
    targetPort: 2369
  selector:
    app: gousers
  sessionAffinity: None
  type: LoadBalancer
